### ISSUE TITLE
Sandbox: Vacuum

### ISSUE THREAD

**Issue by Natejoestev** [codemaker4/codemaker4.github.io#2]
so the "Vacuum" particle in the sandbox is like emptiness right? but if you fill the whole area with Vacuum then add 1 pixel of air somehow the whole area becomes air? vacuums don't create matter, it is literally nothing, no more. (it should just pull particles towards it and fill in. unless you are saying anything out of the area is air? then yes it makes scenes)

**Comment by codemaker4** [comment]
This is just the air expanding in the vacuum. I had plans to add pressure to this sandbox, so the single high pressure pixel fills the vacuum with low pressure.
